// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuwbzjNDWb9nbVOSEEoP7VlSBnoAuIHQ',
    appId: '1:1090122939803:web:d8092d6f4a9c060c53353e',
    messagingSenderId: '1090122939803',
    projectId: 'clothing-project-fdd9e',
    authDomain: 'clothing-project-fdd9e.firebaseapp.com',
    storageBucket: 'clothing-project-fdd9e.firebasestorage.app',
    measurementId: 'G-5WNVRZWTQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcAloDHWA6L3K7MFwriDLlHTR72CUwOY',
    appId: '1:1090122939803:android:e17c05b2b65204ed53353e',
    messagingSenderId: '1090122939803',
    projectId: 'clothing-project-fdd9e',
    storageBucket: 'clothing-project-fdd9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49wtcfvcpYAOqSWbbhM7TPyyGt_My3VQ',
    appId: '1:1090122939803:ios:72a26c77dab8bcb553353e',
    messagingSenderId: '1090122939803',
    projectId: 'clothing-project-fdd9e',
    storageBucket: 'clothing-project-fdd9e.firebasestorage.app',
    iosBundleId: 'com.oumaima.clothingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49wtcfvcpYAOqSWbbhM7TPyyGt_My3VQ',
    appId: '1:1090122939803:ios:72a26c77dab8bcb553353e',
    messagingSenderId: '1090122939803',
    projectId: 'clothing-project-fdd9e',
    storageBucket: 'clothing-project-fdd9e.firebasestorage.app',
    iosBundleId: 'com.oumaima.clothingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvuwbzjNDWb9nbVOSEEoP7VlSBnoAuIHQ',
    appId: '1:1090122939803:web:f05a51d12224a27f53353e',
    messagingSenderId: '1090122939803',
    projectId: 'clothing-project-fdd9e',
    authDomain: 'clothing-project-fdd9e.firebaseapp.com',
    storageBucket: 'clothing-project-fdd9e.firebasestorage.app',
    measurementId: 'G-VPQRJ4X572',
  );
}
